services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
        - LDAP_ORGANISATION=valkey
        - LDAP_DOMAIN=valkey.io
        - "LDAP_BASE_DN=dc=valkey,dc=io"
        - LDAP_ADMIN_PASSWORD=admin123!
    ports:
        - 389:389
        - 636:636

