name: CI

on:
  push:
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

            - name: Install dependencies
              run: |
                sudo apt-get update -y
                sudo apt-get install -y cmake libssl-dev clang-19 clang-tools-19 clang-format-19 libldap-dev netcat-traditional docker-compose ldap-utils

            - name: Build Module
              run: |
                mkdir -p build
                cmake -S . -B build
                cmake --build build --target all -j$(nproc)

            - name: Run tests
              run: |
                ctest --test-dir build --output-on-failure
