name: Clang Format Check

on:
  push:
  pull_request:
    paths:
      - 'src/**'
      - 'test/unit'

jobs:
  clang-format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Clang
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake libssl-dev clang-19 clang-tools-19 clang-format-19
      - name: Run clang-format
        id: clang-format
        run: |
          # Run clang-format and capture the diff
          shopt -s globstar
          clang-format-19 -i src/**/*.c src/**/*.h test/unit/**/*.cpp
          # Capture the diff output
          DIFF=$(git diff)
          if [ ! -z "$DIFF" ]; then
            # Encode the diff in Base64 to ensure it's handled as a single line
            ENCODED_DIFF=$(echo "$DIFF" | base64 -w 0)
            echo "diff=$ENCODED_DIFF" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Check for formatting changes
        if: ${{ steps.clang-format.outputs.diff }}
        run: |
          echo "ERROR: Code is not formatted correctly. Here is the diff:"
          # Decode the Base64 diff to display it
          echo "${{ steps.clang-format.outputs.diff }}" | base64 --decode
          exit 1
        shell: bash
